# Generated by Django 6.0.6 on 2026-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('cantidad', models.FloatField()),
                ('precio_compra', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
